server:  # 서버 관련 설정
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true   # Request, Response에 인코딩 강제

spring:
  datasource:
    driver-class-name: org.mysql.jdbc.Driver
    url: jdbc:mariadb://lourl: jdbc:mysql://localhost:3306/demo
    username: root
    password: 1234
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: create
      use-new-id-generator-mappings: false
    properties:
      hibernate:
        show_sql: false
        format_sql: true
        highlight_sql: true

logging:
  pattern:
    console: "[%d{HH:mm:ss.SSS}][%-5level][%logger.%method:line%line] - %msg%n"
  level:
    org:
      hibernate:
        SQL: debug
        type.descriptor.sql: trace